# Generated by Django 5.2.16 on 2026-08-25 07:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_payee_recurringtransaction_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='NPR', max_length=3, validators=[django.core.validators.RegexValidator(message='Use a three-letter uppercase currency code, for example NPR.', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(default='NPR', max_length=3, validators=[django.core.validators.RegexValidator(message='Use a three-letter uppercase currency code, for example NPR.', regex='^[A-Z]{3}$')]),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 7 to 15 digits, optionally starting with +.', regex='^\\+?[1-9]\\d{6,14}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
