# Generated by Django 5.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_adminverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminverification",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminverification",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
