# Generated by Django 5.2 on 2026-08-26

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_adminverification_failed_attempts_and_locked_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount_limit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Use a signed amount from -Rs 21,00,000 to Rs 21,00,000. Zero is allowed.",
                max_digits=12,
                validators=[
                    MinValueValidator(Decimal("-2100000.00")),
                    MaxValueValidator(Decimal("2100000.00")),
                ],
            ),
        ),
    ]
