# Generated by Django 5.2 on 2026-08-26

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ledger", "0006_alter_budget_amount_limit")]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount_limit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Enter an amount from Rs 0.01 to Rs 21,00,000.",
                max_digits=12,
                validators=[MinValueValidator(Decimal("0.01")), MaxValueValidator(Decimal("2100000.00"))],
            ),
        ),
    ]
